### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#114]
After the last release, we had some significant bugfixes / improvements:

 -  Include predicates in STRtree.query() (# 87)
 -  Add any pygeos/*.dll files for Windows binary .whl files (# 103) 
 -  BUG: Check types in create_collections (# 86) 
 -  ENH: Added total_bounds() (# 107) 
 -  Fix segfault in strtree test_flush_geometries (# 100) 
 -  ENH: Implement hash, eq, neq (# 102)

I think now is a good time for a release. Or is there anything that should go in before? @jorisvandenbossche

**Comment by brendan-ward** [comment]
@caspervdw do we want to try and get #108 into the upcoming release, or should that get held back a little bit to further refine / discuss it's API?  (some investigations and possible changes still underway there - but wondering if I need to try and fast-track additional changes).

It might also be a good time to require GEOS >= 3.6.

**Comment by jorisvandenbossche** [comment]
#108 would indeed be nice to get in (in my case to start using it in geopandas), but releases are cheap, so also fine with already releasing now.

**Comment by caspervdw** [comment]
It's done now, ready to release.

Some points:
 - put a changelog somewhere in the docs
 - put a list of contributors (@brendan-ward @mwtoews #mattijn please supply your full name)
 - after the release, the first wheelbuild on pygeos-wheels can be done (deploy-test should deploy automatically to test - pypi, after that, I have to configure some stuff for the real pypi)

**Comment by caspervdw** [comment]
@mattijn

**Comment by brendan-ward** [comment]
@caspervdw what about using [All Contributors](https://allcontributors.org/) to help track contributors in a standardized way?

**Comment by jorisvandenbossche** [comment]
OK, I already made a release: https://github.com/pygeos/pygeos/releases/tag/0.7
Did not yet upload sdist to PyPI, waiting for the wheels for that first (for which I need merge rights in pygeos-wheels)

---

I also didn't yet do the changelog / list of contributors yet (I thought that should be fine to do after the release as well, since we can update release notes after the fact).

So how do we want to acknowledge contributors? There are several options:

* Maintain an overall list of contributors in some file
  * Eg shapely does this (https://github.com/Toblerity/Shapely/blob/master/CREDITS.txt)
* List all contributors to a certain release
  * This is how I now did it for the 0.7 release: https://github.com/pygeos/pygeos/releases/tag/0.7 (and the same content could be added to the docs), and the same as eg pandas/geopandas does (the list of names is generated with a script).
* More explicitly mention people in the items of the release notes ("By ...")
  * Eg xarray does this https://github.com/pydata/xarray/blob/master/doc/whats-new.rst#new-features
* Use something like All Contributors
  * Eg pyproj does this: https://github.com/pyproj4/pyproj#contributors-

Personally, I would just keep it simple for now. 

Second question is how to include the release notes in the repo. For now I only added them to the actual github releases, but it would be good to add this somewhere in the repo / docs as well. Are we fine with a `history.rst` (or `whatsnew.rst`, `release.rst`, `changelog.rst`, .. whathever name) in the docs, or do people prefer a top-level CHANGELOG.md (or NEWS.md, or ..)

**Comment by brendan-ward** [comment]
👍 on keeping it simple.

👍 on CHANGELOG.md (or CHANGES.md) at top-level; it's easy to find and renders well on Github.  However, there is something to be said to bundling this into the docs as well, like [shapely](https://shapely.readthedocs.io/en/stable/project.html#changes).

**Comment by caspervdw** [comment]
Closing, 0.7.1 is online, with wheels :)
