### ISSUE TITLE
PROPOSAL: function to return all parts of a multi-geometry as ndarray

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#128]
Extracting the individual geometries from a multi geometry / collection is a fairly common task.

In shapely this is available using the `geoms` attribute on multi / collection geometry object.

There doesn't appear to be any counterpart in GEOS, nor does there need to be: it gives us the count of parts and an accessor given an index (plus, it would be hard to consume an array of geometries from GEOS).

Right now, we have to do this in a Python loop, e.g.,
```
parts = [pygeos.get_geometry(g, i) for i in range(0, pygeos.get_num_geometries(g))]
```

Which is certainly not optimal for large numbers of geometries.

There are a number of cases where we would also want to do this for all geometries in an ndarray of source geometries.

A standard ufunc approach doesn't work for this, because the output shape is greater than or equal to the input shape.  It also doesn't look like the generalized ufunc expressions get us here either, though I haven't been able to fully get my head around those.  Is there a way to do this as a ufunc?

Instead, I think we could expose a new function implemented in C that provides this functionality.

Given a singular geometry or 1D array_like of geometries, which returns a 1D array of all parts:

```
>>> geom = pg.Geometry("MULTIPOLYGON (((0 0, 0 10, 10 10, 0 0)), ((1 1, 1 10, 10 10, 1 1)))")
>>> parts = pygeos.get_parts(geom)
array([<pygeos.Geometry POLYGON ((0 0, 0 10, 10 10, 0 0))>, <pygeos.Geometry POLYGON ((1 1, 1 10, 10 10, 1 1))>])
```

For the 1D input case, we may want to know the indexes of the input geometry as well as the parts in order to relate back to the inputs (e.g., for other attributes within a DataFrame).  

In that case, we may want to limit `pygeos.get_parts()` to the single geometry case, and provide `pygeos.get_parts_bulk()` (better name welcome!!  Maybe `get_parts_indexed`?) which returns an array of shape (2,n) where the first array is indexes into source and the second is array of geometries.  

This could leverage some of the existing code used in the ufuncs, so the new code here is mostly in wrapping a bit of C as python functions.

**Comment by jorisvandenbossche** [comment]
Hmm, yes, the scalar geometry vs 1D array of geometries makes this a bit more annoying for a user interface. As indeed, in the first case we don't want the indices. 

I am not sure we right now have functions that *only* work on a scalar though, so that would be a new concept.

But two different functions might make sense.

> which returns an array of shape (2,n) where the first array is indexes into source and the second is array of geometries.

This will need to be 2 separate arrays, since the geometries are object dtype and the indices int dtype.

> This could leverage some of the existing code used in the ufuncs, so the new code here is mostly in wrapping a bit of C as python functions.

Would you propose to basically just put `[pygeos.get_geometry(g, i) for i in range(0, pygeos.get_num_geometries(g))]` into a function on the python side? (as you said, this might not be optimal for large number of geometries / for an large array of geometries)

**Comment by jorisvandenbossche** [comment]
Somewhat equivalent in Postgis is ST_Dump (https://postgis.net/docs/ST_Dump.html), but I don't really find that terminology very clear. They also speak about "expand".

**Comment by brendan-ward** [comment]
For the scalar case, could this instead be a method on a pygeos geometry object instead?

**Comment by caspervdw** [comment]
For the scalar case, I doubt we need any C/Cython extension. The following works and doesn't include a python loop:

```
pygeos.get_geometry(geom, np.arange(n))
```

As you said, it does get more complicated for arrays of geometries as you may have a different amount of sub-geometries per collection. I am :+1: on trying to solve that issue here in pygoes. 

This "ragged array" issue (increasing the dimensionality by 1, with different sizes for each element) relates to sparse arrays (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html). Although I don't think that importing scipy just for this is a good idea, we should have a look at their API.

**Comment by jorisvandenbossche** [comment]
Personally, I don't think we need to make it more complicated as "just" returning an array with the geometries and an array of indices.

(unless I am misunderstanding the relation to scipy sparse matrices)

**Comment by caspervdw** [comment]
Following up on @brendan-ward reference to `np.intersect1d`, I think we can agree on just returning an array of geometries along with an array of indices. 

I was thinking a while on pushing this to the N-dimensional case, but this appeared to be not an option, as these 'ragged' arrays can only be represented as 1D arrays. Consider for example:
```
> get_parts([[collection(a), collection(b, c)], [collection(d), collection(e)]])
```
There is no way you can get the response in a 2D array.

So we can just follow the API of `np.intersect1d` (or `np.in1d`) and ravel the input array before `get_parts`. Also I'd like the `return_indices` kwarg. The response in this example would be:

```
> get_parts([[collection(a), collection(b, c)], [collection(d), collection(e)]])
ndarray([a, b, c, d, e])
> get_parts([[collection(a), collection(b, c)], [collection(d), collection(e)]], return_indices=True)
ndarray([a, b, c, d, e]), ndarray([0, 1, 1, 2, 3])
```

Note that one can always reconstruct the multiindices into the original array with `np.unravel_index`.
