### ISSUE TITLE
Distance Runtime Warnings

### ISSUE THREAD

**Issue by gzheng92** [pygeos/pygeos#167]
I'm experiencing odd behavior across multiple installs of pygeos.

```
import pygeos
a = Geometry("Point (-121.87706 37.334853)")
b = Geometry("Polygon ((-121.885686 37.34214, -121.885686 37.34214, -121.885776 37.342109, -121.88575 37.342063, -121.885579 37.342121, -121.885605 37.342168, -121.885686 37.34214))")
distance(a, b) % This returns a runtime warning, but returns a number that seems right
distance(Geometry("Point (0 0)"), b) % This does not result in any warnings
```

By casual inspection, it's clear that point a is distinct from polygon b, and in any case that shouldn't cause issues.  The warning is:
> ...pygeos/measurement.py:51: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

I suspect the issue is caused by the fact that the polygon has repeated coordinates.  However, `is_simple` failed to detect this.

**Comment by brendan-ward** [comment]
I can reproduce on `master` as well, and using `hausdorff_distance` as well, but not `frechet_distance`.

This does not appear to be a warning specifically raised in `pygeos`; it appears to originate from `GEOS`.

Forcing the warnings to repeat shows that the error is raised for `Point (0 0)` as well:
```
>>> warnings.simplefilter('always', UserWarning)
>>> pg.distance(Geometry("Point (0 0)"),b)
measurement.py:55: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
127.47756025647763
```

If you first normalize the geometry, it avoids the warning:
```
b1 = pygeos.normalize(b)
>>> pg.distance(a,b1)
0.011198088452948665
```

This does not drop any coordinates, but rotates the polygon so that the first coordinate is not repeated:
```
>>> pygeos.to_wkt(b, 10)
'POLYGON ((-121.885686 37.34214, -121.885686 37.34214, -121.885776 37.342109, -121.88575 37.342063, -121.885579 37.342121, -121.885605 37.342168, -121.885686 37.34214))'
>>> pygeos.to_wkt(b1, 10)
'POLYGON ((-121.885776 37.342109, -121.885686 37.34214, -121.885686 37.34214, -121.885605 37.342168, -121.885579 37.342121, -121.88575 37.342063, -121.885776 37.342109))'
```

**Comment by gzheng92** [comment]
Thank you for the prompt and thorough explanation

**Comment by jorisvandenbossche** [comment]
Such "RuntimeWarning: invalid value encountered in ..." typically comes from numpy ufuncs when some invalid floating point operation is done (typically involving a NaN). See https://numpy.org/doc/stable/reference/generated/numpy.seterr.html, and eg:

```
In [11]: np.array([1, np.nan]) > 0
<ipython-input-11-59b85fb31d1e>:1: RuntimeWarning: invalid value encountered in greater
  np.array([1, np.nan]) > 0
Out[11]: array([ True, False])
```

So this might indicate something in the ufunc definition is causing this, since it is coming from our custom `distance` ufunc.

**Comment by jorisvandenbossche** [comment]
Although I don't directly see anything in the ufunc used for distance:

https://github.com/pygeos/pygeos/blob/41251310d1754ae45c7528cbfdf2c015006f3d90/src/ufuncs.c#L835-L864

There are a few cases where we set the result to NaN, but we don't compare anything to NaN or so, and it's also strange that it happens for the case above, which just returns numbers.

@brendan-ward sorry I missed this:

> This does not appear to be a warning specifically raised in pygeos; it appears to originate from GEOS.

Is there a reason to know that this comes from GEOS? Or is it just from the observation that it is fixed by normalizing, so therefore probably comes from GEOS? (I don't know how numpy ufuncs would then capture this and turn into a warning of this class, though)

**Comment by brendan-ward** [comment]
@jorisvandenbossche I don't know, it was a guess.  I didn't find something obvious in GEOS where it was being emitted.

I thought it could be coming here: https://github.com/pygeos/pygeos/blob/e18bc0772b2eb1cb58fb603ff8a73c3a422bb5a1/src/geos.h#L55

But I see that is only on master and not out in installable packages yet.

I didn't consider that it might be coming from the numpy ufunc, just that we aren't specifically doing a custom operation that should trigger this.
