### ISSUE TITLE
BUG: boundary of MultiPolygon is None

### ISSUE THREAD

**Issue by martinfleis** [pygeos/pygeos#184]
PyGEOS seems to return `None` instead of MultiLineString in `pygeos.boundary` if you pass MultiPolygon in.

```py
import geopandas as gpd
import pygeos

df = gpd.read_file(gpd.datasets.get_path('nybb'))  # MultiPolygon geometry

pygeos.boundary(df.geometry.values.data)
-> array([None, None, None, None, None], dtype=object)
```
While shapely returns expected MultiLineString.
```py
df.geometry.iloc[0].boundary.type
-> 'MultiLineString'
```

**Comment by jorisvandenbossche** [comment]
Ah, good catch. 
So in Shapely / GEOS, the boundary method returns an exception if you have a GeometryCollection ("IllegalArgumentException: Operation not supported by GeometryCollection").

In PyGEOS, we typically avoid raising an exception for such cases (because if you have an array of mixed geometries, it is otherwise annoying to get the boundary of the others). But it seems the type check here is too strict (`typ > 3` also includes all "Multi" geoms) :

https://github.com/pygeos/pygeos/blob/a3470e933c9e68efab8e33c978faf7f05443b270/src/ufuncs.c#L203-L212
