### ISSUE TITLE
BUG: `difference` hangs/crashes in some case

### ISSUE THREAD

**Issue by abey79** [pygeos/pygeos#195]
Hello,

@LoicGoulefert and I have been tracking a weird hang with `pygeos.set_operations.difference` which I could reduce to the following test case:

### Setup

macOS 10.15.6
Python version 3.8.5 from MacPort
Clean venv with:
```
$ pip freeze
numpy==1.19.2
pygeos==0.8
$ port installed | grep geos
  geos @3.8.1_0 (active)
```

Code:

```python
import pickle

import numpy as np
import pygeos

with open("lines.pickle", "rb") as fp:
    lines = pickle.load(fp)

with open("coords.npy", "rb") as fp:
    coords = np.load(fp)

line_arr = np.array([pygeos.linestrings(l) for l in lines])
p = pygeos.polygons(coords)

print(f"All lines valid: {np.all(pygeos.is_valid(line_arr))}")
print(f"Polygon valid: {pygeos.is_valid(p)}")
print("Starting...")
pygeos.set_operations.difference(line_arr, p)
print("Done...")
```

Here is a zip containing this script, the data files, and a script to display the datafile's content: [difference_bug.zip](https://github.com/pygeos/pygeos/files/5255797/difference_bug.zip)

Here is what the data looks like:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/49431240/93776231-a4f81c80-fc23-11ea-999b-4c32c53e70d6.png">

In red, about 100 line strings loaded in `line_arr`. In blue, the polygon `p`.

### Expected

Code runs quickly.

### Actual

`pygeos.set_operations.difference()` never returns (or takes a long, long time), with CPU running at 100%.

```
$ python bug_repro.py 
All lines valid: True
Polygon valid: True
Starting...
^C^C^C^C^C^C^CKilled: 9
```
(finally killed from the process manager)

Any idea on what is going on?

**Comment by brendan-ward** [comment]
I am able to reproduce on Mac, GEOS 3.8.0, `pygeos` tip of `master` branch.

It looks like the lines at indices in the range 77 - 86 hang or are unexpectedly slow; all others appear to return (<77 return very fast)

As a first pass, using STRtree to figure out those that intersect first could speed things up:

```python
tree = pygeos.STRtree(line_arr)
subset = line_arr[tree.query(p, predicate='intersects')]
```

This brings it down to the 2 lines that intersect, which then comples much more quickly:
```
pygeos.set_operations.difference(subset, p)
```

Given the direction of the `difference` operation, you would want to copy the full linestrings for all other lines in line_arr to your output (the difference is the original line in each case)

Not sure why some of those that don't intersect are so slow / hang; checking that they intersect is very fast in all cases.

**Comment by brendan-ward** [comment]
There is something really wild going on at the tip of the slow lines.

Example 1:
![image](https://user-images.githubusercontent.com/3375604/93790342-c6d3ae00-fbe7-11ea-896d-1435e002d81f.png)

Example 2:
![image](https://user-images.githubusercontent.com/3375604/93790783-4792aa00-fbe8-11ea-80ad-c5be9b3cc41d.png)

This area was very slow to render in QGIS.  These look like unexpected noise in a sensor?  I suggest passing these through a filter to reduce nodes that are within a tolerance of each other.  At first glance, these tips of the line strings look to be bouncing around at higher precision than I see between other nodes in the linestrings, so it might be as easy as calculating the distance between each pair of vertices and dropping those within some tolerance unless they are endpoints of the line.

These look like they have many self-intersections, so I'm not sure why GEOS is indicating that these are valid (using `pygeos.make_valid` also doesn't clean up underlying issue)

**Comment by abey79** [comment]
So this is an upstream issue if I understand correctly?

Sure enough, this simple change resolves the issue:
```python
pygeos.set_operations.difference(pygeos.simplify(line_arr, 0.01), p)
```

**Comment by brendan-ward** [comment]
Thanks for testing more broadly and reporting back.  Please consider opening an issue in the GEOS issue tracker and adding a link here.  We'll likely close this issue shortly as this isn't an issue with pygeos, but would be good to track the underlying issue with GEOS.

**Comment by abey79** [comment]
@brendan-ward Done, thanks for your help!

**Comment by dr-jts** [comment]
The reason that `difference(lines, polygon)` runs so slowly is that the overlay algorithm in GEOS computes the fully-noded topology graph of **all** the inputs before determining the result of the overlay.   As pointed out above, the lines dataset contains a very large number of self-intersections.  This requires substantial processing to node.  (Consider that the input contains only 100 lines with 138K points, while the difference output contains over **250K noded lines** with **over 600K points**!)

This is by design - noding and topology building is a core function of the overlay algorithm.  If noding the full input is not desired, then simply compute the difference piecewise on the set of lines and (if needed) combine the result.  As noted above, a spatial index can be used, although for this input I'm not sure it's necessary.

I also point out that self-intersecting LineStrings are valid according to the OGC spec.  That is not a factor in this case.

It does seem to be the case that the current GEOS overlay algorithm has a hard time processing this case.  Happily, there is a completely new GEOS overlay implementation which is going to be released [shortly](https://lists.osgeo.org/pipermail/geos-devel/2020-September/009670.html), and it appears to handle this case much better (less memory and faster).

**Comment by dr-jts** [comment]
That is a very cool dataset.  How was it generated?

**Comment by brendan-ward** [comment]
Thank you so much @dr-jts for the detailed follow-up on this!  Your explanation of how this interacts with noding and associated very large increase in noded lines / points is informative for those of us that are less familiar with the internal algorithms of GEOS.  That will be helpful for us to keep in mind as we troubleshoot issues here.

**Comment by abey79** [comment]
Thanks a lot for the detailed follow-up @dr-jts.

The dataset is trajectories of agents whose motion is determined by 4D [Perlin noise](https://en.wikipedia.org/wiki/Perlin_noise). The first two dimensions are used as speed vector for the agent (added to a base speed, so as to have a general flow in a given direction). The 3rd dimension is time (aka simulation steps). And the fourth dimension is agent number. Since successive agents have their velocity profile sampled "nearby" in the Perlin space's 4th dimension, they have a similar trajectory. Thus the global coherence of the agent population.

**Comment by dr-jts** [comment]
Another note:  it is often faster to test whether two geometries intersect before computing their difference (or intersection), since predicates are usually faster than overlay.  This is particularly true in this case.  When computing piecewise difference, the performance is 55 s without a preliminary intersection test, but only **124 ms** with one!

This test is not included as part of the overlay algorithm for the following reasons:
* it is relatively expensive to perform this check in all situations, so it is left up to the client to determine if it is advantageous to do so
* a client might use spatial indexing methods to filter out non-intersecting geometries
* using an intersects filter means that the overlay results might not fulfill the overlay contract of providing fully-noded resulits (since when using a filter the original input value might be returned unchanged).

**Comment by abey79** [comment]
That makes sense, and pygeos handles this beautifully:
```python
idx = pygeos.intersects(line_arr, p)
line_arr[idx] = pygeos.difference(line_arr[idx], p)
```
