### ISSUE TITLE
line_interpolate_point with MultiLineString returns POINT EMPTY for GEOS < 3.8.0

### ISSUE THREAD

**Issue by mwtoews** [pygeos/pygeos#206]
Using pygeos with GEOS 3.7.1, `line_interpolate_point` behaves differently, see implementation in [src/ufuncs.c](https://github.com/pygeos/pygeos/blame/7a2798ab8ef43acf59e2023b8cfcb49e6d9384d3/src/ufuncs.c#L341-L365).

```python
import pygeos
multiline = pygeos.Geometry('MULTILINESTRING ((0 0, 2 0), (3 0, 3 6))')
pygeos.line_interpolate_point(multiline, 0)
```
this returns `POINT EMPTY` with GEOS 3.7.1. The expected result is `POINT(0 0)`, as correctly returned with GEOS >= 3.8.0.

**Comment by jorisvandenbossche** [comment]
So the problem is that the custom GEOS < 3.8 workaround to avoid a segfault for empty linestrings doesn't work for multilinestrings, since those "have 0 points", apparently:

```
In [2]: pygeos.get_num_points(multiline)
Out[2]: 0
```

So we should additionally add a check for the geometry type id being a linestring (or if empty multilinestring also segfaults with older geos, we need to add a check for `(GEOSGeomTypeId_r(context, geom) == 5) && (GEOSGetNumGeometries_r(context, geom) == 0)`

**Comment by caspervdw** [comment]
I'll have a look at this one.
