### ISSUE TITLE
BUG: pygeos.bounds GEOSException with points with np.nan coordinates

### ISSUE THREAD

**Issue by martinfleis** [pygeos/pygeos#231]
`pygeos.bounds` called on a point with nans as coordinates returns a strange `GEOSException`. I guess this should return `
(nan, nan, nan, nan)` as shapely does. I've just encountered this in wild after creating points from DataFrame with missing values.

```py
import pygeos
import numpy as np

pygeos.bounds(pygeos.points([[0, 1], [1, 2], [np.nan, np.nan]]))
```
```
---------------------------------------------------------------------------
GEOSException                             Traceback (most recent call last)
<ipython-input-55-d4f4c24448b6> in <module>
----> 1 pygeos.bounds(pygeos.points([[0, 1], [1, 2], [np.nan, np.nan]]))

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pygeos/decorators.py in wrapped(*args, **kwargs)
     53             for arr in array_args:
     54                 arr.flags.writeable = False
---> 55             return func(*args, **kwargs)
     56         finally:
     57             for arr, old_flag in zip(array_args, old_flags):

/opt/miniconda3/envs/geo_dev/lib/python3.7/site-packages/pygeos/measurement.py in bounds(geometry, **kwargs)
     81     geometry_arr = np.asarray(geometry, dtype=np.object)
     82     out = np.empty(geometry_arr.shape + (4,), dtype="float64")
---> 83     return lib.bounds(geometry_arr, out=out, **kwargs)
     84 
     85 

GEOSException: IllegalArgumentException: Points of LinearRing do not form a closed linestring
```

**Comment by jorisvandenbossche** [comment]
Thanks for the catch!

Seeing that, we should maybe also consider creating empty points instead of "POINT (nan nan)" in the `points()` ufunc (that matches more the intent I think, when using NaN in the x / y arrays to indicate missing values). That's actually what we do with WKT (what I was first doing to try to reproduce this with a single point ..):

```
In [27]: pygeos.bounds(pygeos.Geometry("POINT (nan nan)"))
Out[27]: array([nan, nan, nan, nan])

In [28]: pygeos.Geometry("POINT (nan nan)")
Out[28]: <shapely.geometry.Point POINT EMPTY >
```

Both our roundtrips through WKT or WKB now convert to an empty point:

```
In [30]: point_nan = pygeos.points([np.nan, np.nan])

In [31]: pygeos.from_wkt(pygeos.to_wkt(point_nan))
Out[31]: <shapely.geometry.Point POINT EMPTY >

In [32]: pygeos.from_wkb(pygeos.to_wkb(point_nan))
Out[32]: <shapely.geometry.Point POINT EMPTY >
```

(for WKB this a conscious choice because there is otherwise no way to represent an empty point, so we use the WKB of Point(nan, nan) to do that. For WKT I *think* it is actaully GEOS that does this).

--- 

That said, we should still fix the case you mention though (as there are other ways you can end up with such NaN points, I suppose).

**Comment by caspervdw** [comment]
The GEOS bounds function can't deal with the `NaN` coordinates apparently. I think we should avoid NaN coordinates altogether (see #323)

**Comment by caspervdw** [comment]
Could you check if the issue still persists with GEOS 3.10 ?

**Comment by martinfleis** [comment]
> Could you check if the issue still persists with GEOS 3.10 ?

Seem to be resolved.

```py
>>> import pygeos
>>> import numpy as np
>>> 
>>> pygeos.bounds(pygeos.points([[0, 1], [1, 2], [np.nan, np.nan]]))
array([[ 0.,  1.,  0.,  1.],
       [ 1.,  2.,  1.,  2.],
       [nan, nan, nan, nan]])
```

**Comment by caspervdw** [comment]
I hoped so, thanks for testing that.
