### ISSUE TITLE
Port ST_Line_SubString from PostGIS

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#352]
I needed to cut substrings from lines, and apparently there is no function yet in pygeos/geos c api that does that.

We could port it from PostGIS: https://postgis.net/docs/manual-1.5/ST_Line_Substring.html

**Comment by jorisvandenbossche** [comment]
For reference, Shapely has a pure-python version (and using `line_interpolate_point`) for this called `substring`: https://github.com/Toblerity/Shapely/blob/d37eed96b95747481be3ca582f1028b2623508f6/shapely/ops.py#L568-L689

**Comment by caspervdw** [comment]
I wasn't aware of it, but glancing over it it is similar to what I implemented. This will definitely benefit from a Cython / C implementation.

**Comment by brendan-ward** [comment]
Related work: I recently had to implement something similar to cut a LineString by one or more points (more generically); [here is my current implementation](https://github.com/astutespruce/sarp-connectivity/blob/f725527d200ad1791308c737714d24f7a9839c49/analysis/lib/geometry/lines.py#L41).
(note: this doesn't handle negative indexing to reverse nor returning a point if endpoints of substring are same)

This does indeed seem like it would benefit from Cython / C implementation.  I didn't yet explore that because this is not a performance bottleneck in my analysis pipeline.

There are certainly some API questions to work out here.  I could see us wanting to expose a few functions around this:
- substring: inputs are LineString and start / end point distance or fraction on substring; return LineString (I'm not keen on this returning Point in the case of start = end point after projecting onto the LineString, not sure if we should raise an empty linestring in that case instead - so that we always return LineStrings).  


- cut line: inputs are LineString, Points, and index array of points onto LineStrings (so that we can have uneven number of points per Line); return ndarray of LineStrings and ndarray of line indexes, or a MultiLineString per input LineString.  This could be like my implementation and only return output LineStrings for valid substrings within input LineStrings (i.e., points beyond endpoint of LineString are ignored, duplicate points after projection onto line are ignored, etc)

This could also take an ndarray of start and end distance or fraction along input LineStrings (and associated indexes) to follow similar API as above, and projecting Points onto LineString to obtain these distances / fractions being the caller's responsibility.  (this is probably better form, since it extends nicely from the above from a singular case to a multi case)

So maybe we'd have:
- `substring(geometries, start_dist, end_dist)` where each is an ndarray, or `substring(geometries, [[start_dist1, end_dist1], ...])` where the second parameter is an ndarray of start and end distance pairs
- `substring_all(geometries, start_dist, end_dist, indexes)` or `substring_all(geometries, [[start_dist1, end_dist1], ...], indexes)` where indexes allow us to extract multiple start / end distances from those arrays per input LineString.

**Comment by caspervdw** [comment]
For reference, I copied my implementation into a gist. It takes multiple linestrings and multiple (start, end) for each linestring.

https://gist.github.com/caspervdw/048c46e11071c745cfefd4a4bdb9b770

It seem to be the second option you proposed. I think that actually the `indexes` should not be necessary, if the algorithm can recognize identical input geometries.
