### ISSUE TITLE
Investigate cibuildwheel

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#354]
I recently tried out https://cibuildwheel.readthedocs.io/ for building wheels on github actions, and I must say, it is really convenient to use. I only did a small part (only the 64-bit Linux builds, and without a custom library like GEOS) but I think it must be easy to setup here as well.

@jorisvandenbossche @brendan-ward   Do you have any preference on this?

**Comment by brendan-ward** [comment]
This looks promising.  I haven't built more complex binary wheels against C / C++ libs on CI services yet, so I don't have a strong preference or recommendation here.

**Comment by jorisvandenbossche** [comment]
My first reaction was: my preference is to use the tools that other packages like numpy and pandas etc in the ecosystem are also using (for familiarity with those, ensuring it gets maintained etc). But I see that cibuildwheel was recently "adopted" by the PyPA (https://twitter.com/RomanYurchak/status/1395100234435502088) and for example scikit-learn started to use it as well (they switched from multibuild): https://github.com/scikit-learn/scikit-learn/pull/17921

So +1 on trying that, and since out other wheel infrastructure (travis ..) is down at the moment, I started experimenting a bit with your WIP PR.
