### ISSUE TITLE
Question on intersection set operations

### ISSUE THREAD

**Issue by LunarEngineer** [pygeos/pygeos#359]
I apologize, but I've not been able to parse this from either the documentation or the code; if there's a better place to go and get answers for this you may simply point me in that direction.

I am trying to clarify the operation conducted with intersection when given two arrays of equal length as input.

I've got somewhere around 1e7 instances of data; that data has already gone through a spatial join and now associates (for every instance of data) a left side and right side polygon via an STRTree.query_bulk() operation.

## Naive Belief

I'm now attempting to calculate the area of intersection of the two polygons, naively, and I think I'm misunderstanding; I thought the application of the intersection was vectorized, meaning that, if given two arrays $A$ and $B$ of equal length as input, it would walk down array $A$ and $B$ and for every index $i$ would calculate the intersection of $A_i$ with $B_i$.

Is this actually what intersection is doing, or is it attempting, for every index $i$ in $A$ to calculate the intersection with every index $j$ in $B$?

Does intersection_all, then, produce the vectorized application when given an axis to produce computation over?

**Comment by brendan-ward** [comment]
Intersection is indeed vectorized.  Given each geometry pair in A and B (two input arrays of equal length) it calculates the intersection of each into an output array of same length as input arrays.  This is what you should be doing with the pairs of left and right that you get back via `query_bulk()`.

It will also handle broadcasting in the same way as numpy, which means that A can be arbitrary in length and if B is length 1, then B is broadcast to be the same length as A, and the output is the length of A. (i.e., intersecting single geometry in B with each geometry in A, individually).

`intersection_all` intersects all geometries within a single array together at once (with default axis), producing a single output value.  If you have nested arrays of equal length that you use as input, then `axis` keyword controls how those are intersected together within each nested array.  E.g., an input array of shape (2,3) (i.e., 2 sub arrays of 3 items each):
* `axis=None` (default): output is a single geometry
* `axis=0`: output is length 3
* `axis=1`: output is length 2 (intersect all geometries with each other within each nested array)

Are you running into issues with intersection?  It can be performance-intensive, especially with that many pairs.

**Comment by LunarEngineer** [comment]
I'm on PyGeos 0.9, bythe way.

**Comment by brendan-ward** [comment]
Do you have something else you are comparing those runtimes to?  Processing time is highly dependent on the complexity of each geometry in each pair, even if they only have a small overlap there is a big performance impact of many vertices outside the area of intersection.  Can you tell us more about the nature of your geometries and the degree of their overlap?

Pygeos when used directly is not parallelized; it will use a single thread by default.  Most of the operations are thread-safe and you can use them across multiple threads with something like Dask.  See https://caspervdw.github.io/Pygeos-Multithreading/ for more info on this.

**Comment by LunarEngineer** [comment]
Ok, that definitely answers my questions and I appreciate it; I didn't have much to compare it to, so wanted to check my understanding of the documentation first.

One side of the set of polygons has a very small number of vertices; so small that it's under a handful for every instance of data. The other side has polygons which are significantly more complex and can contain an arbitrary number of vertices; there's a many to many relationship so I could do some modestly intelligent grouping of sub-tasks and parallelize it do a great degree.

You say 'when used directly'. Is there a package which already implements spatial joins and more complex geospatial operations using PyGEOS? I've seen the chatter about GeoPandas and Shapely updates, but I'm not aware if there are plans within the 'future close enough to be useful for the project' timeframe.

**Comment by LunarEngineer** [comment]
I'd like to close the issue, unless you'd like it kept open for some reason?

**Comment by martinfleis** [comment]
You can use [`dask_geopandas`](https://github.com/geopandas/dask-geopandas) to parallelise that intersection.

```py
import dask_geopandas

# I am assuming that `zipped` is a geopandas.GeoDataFrame

dask_zipped = dask_geopandas.from_geopandas(zipped, npartitions=64)

intersections = zipped.geometry_x.intersection(dask_zipped.geometry_y)
intersections = intersections.compute()
```

This will return a GeoSeries of intersections and perform the operation multi-threaded.

**Comment by LunarEngineer** [comment]
Thanks Martin! I definitely appreciate that.

**Comment by brendan-ward** [comment]
> 'when used directly'

I meant that when you use pygeos by itself but not some other package that enables you to divide the arrays into chunks like Dask or dask_geopandas.

GeoPandas implements spatial joins, and leverages pygeos if you have it installed.  Definitely worth checking out the GeoPandas docs to see if it provides other things that you may need.

I've had some luck using intermediate clipping to speed up intersections like this (polygons that have many vertices outside the intersected area).  The approach goes something like this (A, B refer to geometry arrays, `a`, `b` refers to the first geometry pair):
1. use `query_bulk` to find all pairs between A and B, and join in the geometries so that you have original indexes from A and B and your geometries, with columns like `a_index`, `a_geometry`, `b_index`, `b_geometry`
2. calculate envelopes (`pygeos.envelope()`) for A and B, and join them to the above based on their indexes `a_index`, etc
3. use `pygeos.contains()` or `pygeos.contains_properly()` to find all cases where `a` contains `b` => output is `b`
4. similar to above, find all cases where `b` contains `a` => output is `a`
5. following methods are just for those that are not already assigned an output and are applied to the entire arrays.  Intersect the envelope for A with the envelope for B
6. use the bounds from that intersection, expand by small value, and create clipping rectangle coordinates for each pair; we can now clip A and B to the area where there bounding boxes overlap
7. use `pygeos.clip_by_rect` to clip A using that clipping rectangle and clip B by that clipping rectangle too.  Read the docs for this function; there are caveats to using it; it is fast but possibly may not work properly for your data.
8. you now have a much smaller clipped A and clipped B.  Intersect these as you are doing now; the intersection should be faster IF the polygons are very complex, have many vertices outside the intersected area, and the overhead of the above functions is not too bad for your specific data.
