### ISSUE TITLE
Function required to fix self-intersection

### ISSUE THREAD

**Issue by tengerye** [pygeos/pygeos#421]
Hi, there is `is_simple()` to check if a Geometry is self-intersection, but I could not find one for converting a self-intersection to non-intersection. May I ask if I miss something or there is already an alternative? Or is it too hard to implement please?

**Comment by jorisvandenbossche** [comment]
Does `make_valid()` do what you need?

**Comment by tengerye** [comment]
@jorisvandenbossche Thank you so much, Sir. The name of the function looks good to me. However, the explanations on the document is too brief. How could I find how is it implemented please?

**Comment by brendan-ward** [comment]
See [GEOSisSimple](https://libgeos.org/doxygen/geos__c_8h.html#a0208d08bea6ec9954e5dba0206dff0ce) for a tiny bit more information.  This function is implemented in GEOS and we use it here, so that is the place to look for implementation details.

See also [IsSimpleOp](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/IsSimpleOp.html) in JTS, as this likely is the same algorithm as is used in GEOS, but described in more detail.

**Comment by brendan-ward** [comment]
Closing, since the last request was for implementation details that exist outside this project.
