### ISSUE TITLE
Add support for other types of geometries

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#451]
Support geometries based on curves, e.g. "CompoundCurve".

![image](https://user-images.githubusercontent.com/55836583/175076641-29394ca5-3e6d-435f-8de7-795ae17572d1.png)

**Comment by brendan-ward** [comment]
@carlosg-m was this intended for a different repository, e.g., `pyogrio` or `Fiona` which deal with reading / writing OGR types (what you have listed here)?

Also see: https://github.com/pygeos/pygeos/issues/448
Comments regarding pygeos functionality are now to be directed to the `Shapely` project.

Further, pygeos / Shapely are based on GEOS, which to my understanding does not support compound curve geometry types; since GEOS is our underlying geometry engine, there's nothing we can do to add support for these without it first being in GEOS.
