### ISSUE TITLE
Conversion to Shapely objects

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#54]
For GeoPandas (and for interoperability with Shapely), I need a way to convert geometries from pygeos to Shapely and vice versa.

As discussed in https://github.com/pygeos/pygeos/pull/47, one way is to go through WKB. In that PR I had a way to directly clone the GEOSGeometry pointer, but if pygeos and shapely are not using the same GEOS library, this can cause problems.

However, going through WKB is also not fully faithful. For example, empty points don't have a WKB representation.

**Comment by caspervdw** [comment]
After all I think the performance difference is so large that we can take the risk of incompatible versions. We can just put a warning in the docstring?

I was just working on a `from_shapely` ufunc, for performance comparison, and I find 3.7 ms for `from_shapely` and 123 ms going through WKB.

**Comment by jorisvandenbossche** [comment]
Maybe there would be a way to detect that both are using the same GEOS library, and only do it then.

**Comment by brendan-ward** [comment]
The conversion via pointers to GEOS geometries underneath `shapely` objects was implemented in #61 and works great other than incompatible GEOS versions as mentioned in #122.

Changed the title to reflect that this is about conversion.

The conversion to `shapely` objects is already handled out in `geopandas` where the `shapely` library is available as a core dependency.  In order to provide same here, we'd have to include `shapely` as an optional dependency.

@jorisvandenbossche should this be handled in `pygeos` or downstream libraries as you've done for `geopandas`?

**Comment by jorisvandenbossche** [comment]
As reference, the code in GeoPandas for this conversion is here:

https://github.com/geopandas/geopandas/blob/1b0f006ba1a07f7896d7e5854fa5954ca1d83213/geopandas/_vectorized.py#L61-L74

Given that this uses some semi-private APIs from shapely, it would be nice to not have each downstream library do this, and rather include a `to_shapely` method in pygeos (but given the work to integrate it in shapely itself, which renders this method useless, this is also not the biggest priority for myself)

**Comment by brendan-ward** [comment]
@jorisvandenbossche presumably pygeos merging with shapely to make shapely 2.0 also renders this unnecessary here, but would be handled as part of that process?  I.e., there would just be one set of binary objects involved at that point, instead of 2 as now.  Short term conversion only seems necessary to use pygeos in geopandas in the meantime?

**Comment by jorisvandenbossche** [comment]
Yes, in Shapely 2.0, there will be no conversion needed, as we will just have the shapely geometries. But that said, there are quite some packaging already starting to use pygeos in the meantime, so it's quite plausible they need to do those conversions just like geopandas does. So having a conversion function in pygeos for the time being is certainly not a bad idea IMO.

**Comment by jorisvandenbossche** [comment]
(moved to next milestone, since we don't have active work on this)

**Comment by caspervdw** [comment]
Fixed in #312
