### ISSUE TITLE
Compilation problem on Mac OS / clang

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#89]
See https://github.com/pygeos/pygeos/pull/83

With the current codebase, @sgillies and @vincentsarago report they get the following error:

```
duplicate symbol '_STRtreeType' in:
    build/temp.macosx-10.14-x86_64-3.7/src/lib.o
    build/temp.macosx-10.14-x86_64-3.7/src/strtree.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

Removing an `#include "strtree.h"` solves this, but then results in some warnings (see https://github.com/pygeos/pygeos/pull/83). @sgillies suggests that the better solution would be to have one source file per extension module.

**Comment by jorisvandenbossche** [comment]
> I think the single source file is really the way to go.

@sgillies I think the main reason we split it up in several files, is for code organisation. It would become a really huge single C file if we put everything together. Are there no other solutions to this?

Or, we need to have multiple extension modules if we want to keep sources splitted?

**Comment by caspervdw** [comment]
I am against splitting the source files. This will result in a huge file which is just hard to maintain. We just have to get the headers and includes right. I hope #91 fixes the issue.

**Comment by sgillies** [comment]
@caspervdw I agree about the benefits of small C source files. There is nothing wrong with this from a Python C extension standpoint.

As I see it, the root of the problem is src/lib.c and the way it includes all the other modules. If we want to keep small C modules (I do), I think we should consider changing from the current state of one single extension module that has multiple sources (see https://github.com/pygeos/pygeos/blob/master/setup.py#L110-L114)

```python
module_lib = Extension(
    "pygeos.lib",
    sources=["src/lib.c", "src/geos.c", "src/pygeom.c", "src/ufuncs.c", "src/coords.c", "src/strtree.c"],
    **get_geos_paths()
)
```

to *multiple* extension modules with a single source each:

```python
module_libs = [
    Extension("pygeos._lib", sources=["src/lib.c"]),
    Extension("pygeos._geos", sources=["src/geos.c"]),
    Extension("pygeos._pygeom", sources=["src/pygeom.c"],
    ... # etc.
]
```

In my experience, this is the most "normal" way to make a package of extension modules, and makes simple C builds possible across platforms.
